name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            laravel: ^10.0
            testbench: ^8.0
          - php: 8.3
            laravel: ^10.0
            testbench: ^8.0
          - php: 8.2
            laravel: ^11.0
            testbench: ^9.0
          - php: 8.3
            laravel: ^11.0
            testbench: ^9.0
          - php: 8.2
            laravel: ^12.0
            testbench: ^10.0
          - php: 8.3
            laravel: ^12.0
            testbench: ^10.0
          - php: 8.4
            laravel: ^12.0
            testbench: ^10.0
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, gd
          coverage: xdebug
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key:  ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-progress --prefer-stable --no-interaction

      - name: Run Tests
        run: |
          mkdir -p build/logs
          vendor/bin/pest --coverage-clover=build/logs/clover.xml

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring
          tools: composer:v2

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run Pint
        run: composer lint

  analyse:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring
          tools: composer:v2

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run PHPStan
        run: composer analyse
